language: node_js
node_js:
  - "12"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - git remote add upstream https://github.com/nelidiakonidze/universal.git
  - git fetch upstream master
  - yarn


matrix:
  fast_finish: true
  include:
    - stage: lint
      script: ng lint
    - stage: test
      script: ng test



