language: node_js
node_js: 
  - '12'


install: 
    - git remote add upstream https://github.com/nelidiakonidze/universal.git
    - git fetch upstream master
    - yarn

cache:
  yarn: true
  directories:
    - node_modules

  
matrix:
    include:
    - stage: test
      script: ng lint
      name: 'lint'
      
    - stage: test 
      script: ng test
      name: 'test'
